logo
openMetadataInitiative/openMINDS_MRI pull request #3
Opened 2023-12-11 12:17 UTC by lzehl

2024-02-05 13:27 UTC, Peyman-N approved these changes

2024-07-02 11:20 UTC, Peyman-N commented
This should be changed to reflect the new name.

2024-07-02 11:21 UTC, Peyman-N requested changes

2024-07-02 11:21 UTC, Peyman-N commented on img/openMINDS_MRI_logo_dark.png
This should be changed to reflect the new name.

2024-07-02 23:25 UTC, Peyman-N requested changes
This should be changed to reflect the new name.

2024-07-04 09:14 UTC, lzehl commented
@UlrikeS91 would you be able to take over? I would suggest to reduce the name for the logo to "nimaging" or only "imaging" (if the long name "neuroimaging" does not fit)

2024-07-04 10:53 UTC, UlrikeS91 commented
> @UlrikeS91 would you be able to take over? I would suggest to reduce the name for the logo to "nimaging" or only "imaging" (if the long name "neuroimaging" does not fit)

Yes, I can fix this. Tried a few options now and none of your suggestions fit.  The best alternative I see is: "nImg" (similar to specimenPrep, where we use sPrep). I'll fix it with this abbreviation. If you're absolutely against it, I need a better suggestion that is no longer then 5 characters 😉

2024-07-05 08:50 UTC, lzehl commented
@UlrikeS91 opened a new PR for the updated logos; so I'm closing this one now.

2024-07-05 08:50 UTC, closed without merging